

development:
  adapter: mysql2
  encoding: utf8
  database: development_dataclub
  username: root
  password: 
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  encoding: utf8
  databse: test_dataclub
  username: root
  password:  
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  username: qqpeiljopbiuij
  password: 2J_koQyASn8RyCkEqot-uDLNcl
  database: d6uo01adgsqn94
  host: ec2-54-197-250-52.compute-1.amazonaws.com
  port: 5432
  pool: 5